# Practise Questions - Numpy and Pandas Basics 

**Import the NumPy library before solving the exercises**

### Let's begin with some hands-on practice exercises

<a id="1D"> </a>
## 1. One Dimensional Array

<table align="left">
    <tr>
        <td width="6%">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>1. Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array</b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [94]:
import numpy as np
list_temperature = [3.04,1.65,5.76,1.66,1.54,4.69,2.68] 
new_array = np.array(list_temperature)
new_array

array([3.04, 1.65, 5.76, 1.66, 1.54, 4.69, 2.68])

<table align="left">
    <tr>
        <td width="6%">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>2. Create a 1D array of weights of 10 students and retrieve all the weights greater than 68</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the weights given below: (or create your own list)**

    weights = [74.2, 85, 74, 67.9, 52, 70.5, 86, 51.8, 64, 82]

In [95]:
weights = [74.2, 85, 74, 67.9, 52, 70.5, 86, 51.8, 64, 82]
new_weights = np.array(weights)
a = new_weights[new_weights>68]
a

array([74.2, 85. , 74. , 70.5, 86. , 82. ])

<table align="left">
    <tr>
        <td width="6%">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>3. Write a code to generate 10 random integers between 20 to 40 (Is it possible to generate same random numbers everytime? If yes, describe the function)
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [96]:
np.random.randint(20,40,10)

array([37, 38, 30, 22, 26, 30, 25, 38, 39, 23])

In [97]:
np.linspace(10,20,10,dtype='int')

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 20])

<table align="left">
    <tr>
        <td width="6%">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>4. Write a program to get the fifth power of the first five positive integers
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

<table align="left">
    <tr>
        <td width="6%">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>5. Write a program to create an array of all the odd integers from 50 to 100 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [98]:
np.arange(51,100,2)


array([51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83,
       85, 87, 89, 91, 93, 95, 97, 99])

<table align="left">
    <tr>
        <td width="6%">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>6. Write a program to calculate the sum of each column </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [99]:
a = [[1, 4, 8], [5, 7, 3], [9, 14, 2]]
a1 = np.array(a)
b = a1.sum(axis = 0)
b
#row - 1
#col - 0

array([15, 25, 13])

**Use the array given below: (or create your own array)**

    A = [[1, 4, 8], [5, 7, 3], [9, 14, 2]]

<table align="left">
    <tr>
        <td width="6%">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>7. Write a code to get the element-wise remainder of an array after division by 8 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below:**<br>
    
    num = [42, 87, 90, 14, 32, 75, 61, 80, 92]

In [100]:
num = [42, 87, 90, 14, 32, 75, 61, 80, 92]
numa=np.array(num)
numa%8

array([2, 7, 2, 6, 0, 3, 5, 0, 4], dtype=int32)

<a id="2D"> </a>
## 2. Two Dimensional Array

<table align="left">
    <tr>
        <td width="6%">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>8. Create a 2D numpy array from a 1D array of 20 elements of your choice. Further, subset the first 5 elements from the second element of a resulting 2D array 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [101]:
a=np.arange(1,21).reshape(2,10)

print(a[0:1, 1:6])


[[2 3 4 5 6]]


<table align="left">
    <tr>
        <td width="6%">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>9. Write a program to find common values between two arrays 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below:**<br>

    prices_monday = [10, 30, 50, 60, 90]

    prices_tuesday = [50, 20, 80, 125, 10, 70]

In [102]:
prices_monday = [10, 30, 50, 60, 90,10]
prices_tuesday = [50, 20, 80, 125, 10, 70]
a=np.array(prices_monday)
b=np.array(prices_tuesday)
np.intersect1d(a,b)


array([10, 50])

In [103]:
a=[]
for i in prices_tuesday:
    if i in prices_monday:
        a.append(i)
a
        

[50, 10]

<table align="left">
    <tr>
        <td width="6%">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>10. Write a program to add a new column ([5,7]) at the last position in the array given below 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [104]:
array1 = [[[3, 4], [8, 2],[5, 9]]]
a=np.array(array1)
a
np.insert(a,3,[5,7],axis = 1)

array([[[3, 4],
        [8, 2],
        [5, 9],
        [5, 7]]])

**Use the array given below:**

    array1 = [[[3, 4], [8, 2],[5, 9]]]

<table align="left">
    <tr>
        <td width="6%">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>11. Write a code to print the identity matrix of order 5</b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [105]:
np.identity(3,dtype = 'int')*5

array([[5, 0, 0],
       [0, 5, 0],
       [0, 0, 5]])

<table align="left">
    <tr>
        <td width="6%">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>12. Write a program to transpose a matrix 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the matrix given below:**
    
    M = [[15, 17, 45, 56], [7, 42, 15, 63], [54, 3, 61, 41], [0, 87, 16, 20]]

In [106]:
M = [[15, 17, 45, 56], [7, 42, 15, 63], [54, 3, 61, 41], [0, 87, 16, 20]]
M  = np.array(M)
M.T

array([[15,  7, 54,  0],
       [17, 42,  3, 87],
       [45, 15, 61, 16],
       [56, 63, 41, 20]])

<a id='Data_Structures'></a>
## 1. Data Structures with Examples:

<table align="left">
    <tr>
        <td width="6%">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>1. Write a program to create a dataframe from list of lists
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the below nested list:**<br>

        data = [['Joy', 21], ['Mia', 15], ['Sam', 14]]

In [107]:
import pandas as pd
data = [['Joy', 21], ['Mia', 15], ['Sam', 14]]
a = pd.DataFrame(data)
a

0   1
0  Joy  21
1  Mia  15
2  Sam  14

<table align="left">
    <tr>
        <td width="6%">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>2. Extract the second word from the given string after converting to series
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [111]:
sentence = 'Be confident and be yourself'
newSentence = pd.Series(list(sentence))
newSentence[3:12]

3     c
4     o
5     n
6     f
7     i
8     d
9     e
10    n
11    t
dtype: object

**Use the below string:**<br>
    
    sentence = 'Be confident and be yourself'

<a id='create_manipulate'></a>
## 2. Create and Manipulate the DataFrames:

<table align="left">
    <tr>
        <td width="6%">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>3. Select the rows from below dataframe where marks are less than 60 </b>
                </font>
            </div>
        </td>
    </tr>
</table>

##### Create the  dataframe and do the required manipulation

**Use the dataframe given below:**

<table>
<tr>
<th>Name</th>
<th>Marks</th>
</tr>
<tr>
<td>John</td>
<td>90</td>
</tr>
<tr>
<td>Robert</td>
<td>50</td>
</tr>
<tr>
<td>Jonny</td>
<td>89</td>
</tr>
<tr>
<td>Mia</td>
<td>55</td>
</tr>
   
</table>

In [112]:
data = [["john",90],["robert",50],["jonny",89],["mia",55]]
df = pd.DataFrame(data,columns=["Names","Marks"])
df[df["Marks"]<60]

Names  Marks
1  robert     50
3     mia     55

<table align="left">
    <tr>
        <td width="6%">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>4. Write a program to select the rows where the sales are higher than 60000 for Mumbai </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the dataframe given below:**
   
<table>
<tr>
<th>Store</th>
<th>Location</th>
<th>Sales</th>
</tr>
<tr>
<td>A</td>
<td>Mumbai</td>
<td>40000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>45000</td>
</tr>
<tr>
<td>A</td>
<td>Hyderabad</td>
<td>50000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>90000</td>
</tr>
<tr>
<td>D</td>
<td>Pune</td>
<td>89000</td>
</tr>
<tr>
<td>A</td>
<td>Delhi</td>
<td>87000</td>
</tr>
<tr>
<td>D</td>
<td>Hyderabad</td>
<td>85000</td>
</tr>
<tr>
<td>A</td>
<td>Pune</td>
<td>78000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>89000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>70000</td>
</tr>
   
</table>

In [113]:
df = {"Store":["A","B","A","C","D","A","D","A","C","B"],
      "Location":["Mumbai","Pune","Hyderabad","Mumbai","Pune","Delhi","Hyderabad","Pune","Mumbai","Pune"],
     "Sales":[40000,45000,50000,90000,89000,87000,85000,78000,89000,70000]}
df = pd.DataFrame(df)
sales = df[(df["Location"]=="Mumbai") & (df["Sales"]>60000)]
sales

Store Location  Sales
3     C   Mumbai  90000
8     C   Mumbai  89000

<table align="left">
    <tr>
        <td width="6%">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>5. Write a program to select stores located in Hyderabad</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the dataframe given below:**
   
<table>
<tr>
<th>Store</th>
<th>Location</th>
<th>Sales</th>
</tr>
<tr>
<td>A</td>
<td>Mumbai</td>
<td>40000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>45000</td>
</tr>
<tr>
<td>A</td>
<td>Hyderabad</td>
<td>50000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>90000</td>
</tr>
<tr>
<td>D</td>
<td>Pune</td>
<td>89000</td>
</tr>
<tr>
<td>A</td>
<td>Delhi</td>
<td>87000</td>
</tr>
<tr>
<td>D</td>
<td>Hyderabad</td>
<td>85000</td>
</tr>
<tr>
<td>A</td>
<td>Pune</td>
<td>78000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>89000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>70000</td>
</tr>
   
</table>

In [114]:
stores = df[(df["Location"]=="Hyderabad")]
stores["Store"]

2    A
6    D
Name: Store, dtype: object

<table align="left">
    <tr>
        <td width="6%">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>6. Write a program to replace the 'Store' column with the values A, B, C, and D with Store_A,  Store_B, Store_C and Store_D respectively </b>  
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the dataframe given below:**
   
<table>
<tr>
<th>Store</th>
<th>Location</th>
<th>Sales</th>
</tr>
<tr>
<td>A</td>
<td>Mumbai</td>
<td>40000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>45000</td>
</tr>
<tr>
<td>A</td>
<td>Hyderabad</td>
<td>50000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>90000</td>
</tr>
<tr>
<td>D</td>
<td>Pune</td>
<td>89000</td>
</tr>
<tr>
<td>A</td>
<td>Delhi</td>
<td>87000</td>
</tr>
<tr>
<td>D</td>
<td>Hyderabad</td>
<td>85000</td>
</tr>
<tr>
<td>A</td>
<td>Pune</td>
<td>78000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>89000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>70000</td>
</tr>
   
</table>

In [115]:
#df['Store'] = df['Store'].replace(['A', 'B' ,'C','D'], ['Store_A', 'Store_B' ,'Store_C','Store_D'])
#

print(df)

     Store   Location  Sales
0  Store_A     Mumbai  40000
1  Store_B       Pune  45000
2  Store_A  Hyderabad  50000
3  Store_C     Mumbai  90000
4  Store_D       Pune  89000
5  Store_A      Delhi  87000
6  Store_D  Hyderabad  85000
7  Store_A       Pune  78000
8  Store_C     Mumbai  89000
9  Store_B       Pune  70000


In [61]:
#need to discuss

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>7. Create a dataframe in pandas using the given list.
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the below list**

        city = ['Delhi', 'Mumbai', 'Chennai', 'Kolkata']

In [51]:
city = ['Delhi', 'Mumbai', 'Chennai', 'Kolkata']
pd.DataFrame(city)

0
0    Delhi
1   Mumbai
2  Chennai
3  Kolkata

<table align="left">
    <tr>
        <td width="6%">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>8. Save a given dataframe to a csv file
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the dataframe given below:**
   
<table>
<tr>
<th>Store</th>
<th>Location</th>
<th>Sales</th>
</tr>
<tr>
<td>A</td>
<td>Mumbai</td>
<td>40000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>45000</td>
</tr>
<tr>
<td>A</td>
<td>Hyderabad</td>
<td>50000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>90000</td>
</tr>
<tr>
<td>D</td>
<td>Pune</td>
<td>89000</td>
</tr>
<tr>
<td>A</td>
<td>Delhi</td>
<td>87000</td>
</tr>
<tr>
<td>D</td>
<td>Hyderabad</td>
<td>85000</td>
</tr>
<tr>
<td>A</td>
<td>Pune</td>
<td>78000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>89000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>70000</td>
</tr>
   
</table>

- data1.to_csv('filename.csv')
- data2=pd.read_csv('filename.csv')
- data2

<table align="left">
    <tr>
        <td width="6%">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>9. Find the maximum sales for each store
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the dataframe given below:**
   
<table>
<tr>
<th>Store</th>
<th>Location</th>
<th>Sales</th>
</tr>
<tr>
<td>A</td>
<td>Mumbai</td>
<td>40000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>45000</td>
</tr>
<tr>
<td>A</td>
<td>Hyderabad</td>
<td>50000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>90000</td>
</tr>
<tr>
<td>D</td>
<td>Pune</td>
<td>89000</td>
</tr>
<tr>
<td>A</td>
<td>Delhi</td>
<td>87000</td>
</tr>
<tr>
<td>D</td>
<td>Hyderabad</td>
<td>85000</td>
</tr>
<tr>
<td>A</td>
<td>Pune</td>
<td>78000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>89000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>70000</td>
</tr>
   
</table>

In [116]:
df['Store'] = df['Store'].replace(['Store_A', 'Store_B' ,'Store_C','Store_D'],['A', 'B' ,'C','D'])


df.groupby(["Store"]).agg({"Sales":"max"})

Sales
Store       
A      87000
B      70000
C      90000
D      89000

<table align="left">
    <tr>
        <td width="6%">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>10. Write a program to select all columns, except the 'Location' from the given dataframe
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the dataframe given below:**
   
<table>
<tr>
<th>Store</th>
<th>Location</th>
<th>Sales</th>
</tr>
<tr>
<td>A</td>
<td>Mumbai</td>
<td>40000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>45000</td>
</tr>
<tr>
<td>A</td>
<td>Hyderabad</td>
<td>50000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>90000</td>
</tr>
<tr>
<td>D</td>
<td>Pune</td>
<td>89000</td>
</tr>
<tr>
<td>A</td>
<td>Delhi</td>
<td>87000</td>
</tr>
<tr>
<td>D</td>
<td>Hyderabad</td>
<td>85000</td>
</tr>
<tr>
<td>A</td>
<td>Pune</td>
<td>78000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>89000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>70000</td>
</tr>
   
</table>

In [117]:
#use iloc
df.iloc[:,[0,2]]

Store  Sales
0     A  40000
1     B  45000
2     A  50000
3     C  90000
4     D  89000
5     A  87000
6     D  85000
7     A  78000
8     C  89000
9     B  70000

<table align="left">
    <tr>
        <td width="6%">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>11. Write a program to insert a given column at the second position in a dataframe
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the dataframe given below:**

<table>
<tr>
<th>Name</th>
<th>Age</th>
</tr>
<tr>
<td>Emma Larter</td>
<td>34</td>
</tr>
<tr>
<td>Mia Junior</td>
<td>59</td>
</tr>
<tr>
<td>Sophia Depp</td>
<td>32</td>
</tr>
<tr>
<td>James Smith</td>
<td>40</td>
</tr>
   
</table>

**Add the variable 'Salary' as second column**<br>
            
            Salary = [35000, 24000, 55000, 40000]

In [118]:
df_new = {"Name":["Emma Larter","Mia Junior","Sophia Depp","James Smith"],"Age":[34,59,32,40]}
df_new = pd.DataFrame(df_new)
Salary = pd.DataFrame([35000, 24000, 55000, 40000])
df_new.insert(1,"Salary",Salary)
df_new

Name  Salary  Age
0  Emma Larter   35000   34
1   Mia Junior   24000   59
2  Sophia Depp   55000   32
3  James Smith   40000   40

<table align="left">
    <tr>
        <td width="6%">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>12. Write a program to get the third observation of the given dataframe
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the dataframe given below:**

<table>
<tr>
<th>Name</th>
<th>Age</th>
</tr>
<tr>
<td>Emma Larter</td>
<td>34</td>
</tr>
<tr>
<td>Mia Junior</td>
<td>59</td>
</tr>
<tr>
<td>Sophia Depp</td>
<td>32</td>
</tr>
<tr>
<td>James Smith</td>
<td>40</td>
</tr>
</table>    

In [119]:
df_new.iloc[2]

Name      Sophia Depp
Salary          55000
Age                32
Name: 2, dtype: object

<table align="left">
    <tr>
        <td width="6%">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>13. Write a program to create a dataframe from the provided lists</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the following lists to create your arrays:**
        
            columns = ["Science", "Maths", "English"]
            
            marks = [[55, 78, 88], [93, 63, 83],[94, 74, 64]]
            
**Hint:** Convert the list marks into an array           

In [120]:
marks = [[55, 78, 88], [93, 63, 83],[94, 74, 64]]
df_sub = pd.DataFrame(marks,columns = ["Science", "Maths", "English"])
df_sub

Science  Maths  English
0       55     78       88
1       93     63       83
2       94     74       64

<table align="left">
    <tr>
        <td width="6%">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>14. Write a program to count total sales per store </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the dataframe given below:**
   
<table>
<tr>
<th>Store</th>
<th>Location</th>
<th>Sales</th>
</tr>
<tr>
<td>A</td>
<td>Mumbai</td>
<td>40000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>45000</td>
</tr>
<tr>
<td>A</td>
<td>Hyderabad</td>
<td>50000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>90000</td>
</tr>
<tr>
<td>D</td>
<td>Pune</td>
<td>89000</td>
</tr>
<tr>
<td>A</td>
<td>Delhi</td>
<td>87000</td>
</tr>
<tr>
<td>D</td>
<td>Hyderabad</td>
<td>85000</td>
</tr>
<tr>
<td>A</td>
<td>Pune</td>
<td>78000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>89000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>70000</td>
</tr>
   
</table>

In [121]:

count = df.groupby(["Store"]).agg({"Sales":"sum"})
count

Sales
Store        
A      255000
B      115000
C      179000
D      174000

<a id='sorting'></a>
## 3. Sort

<table align="left">
    <tr>
        <td width="6%">
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>15. Write a program to sort the dataframe by 'Sales' in ascending order
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the dataframe given below:**
   
<table>
<tr>
<th>Store</th>
<th>Location</th>
<th>Sales</th>
</tr>
<tr>
<td>A</td>
<td>Mumbai</td>
<td>40000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>45000</td>
</tr>
<tr>
<td>A</td>
<td>Hyderabad</td>
<td>50000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>90000</td>
</tr>
<tr>
<td>D</td>
<td>Pune</td>
<td>89000</td>
</tr>
<tr>
<td>A</td>
<td>Delhi</td>
<td>87000</td>
</tr>
<tr>
<td>D</td>
<td>Hyderabad</td>
<td>85000</td>
</tr>
<tr>
<td>A</td>
<td>Pune</td>
<td>78000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>89000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>70000</td>
</tr>
   
</table>

In [122]:
df.sort_values(by="Sales")

Store   Location  Sales
0     A     Mumbai  40000
1     B       Pune  45000
2     A  Hyderabad  50000
9     B       Pune  70000
7     A       Pune  78000
6     D  Hyderabad  85000
5     A      Delhi  87000
4     D       Pune  89000
8     C     Mumbai  89000
3     C     Mumbai  90000

<table align="left">
    <tr>
        <td width="6%">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>16. Write a program to sort the dataframe by 'Store' in ascending order and by 'Sales' in descending order with respect to store simultaneously
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the dataframe given below:**
   
<table>
<tr>
<th>Store</th>
<th>Location</th>
<th>Sales</th>
</tr>
<tr>
<td>A</td>
<td>Mumbai</td>
<td>40000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>45000</td>
</tr>
<tr>
<td>A</td>
<td>Hyderabad</td>
<td>50000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>90000</td>
</tr>
<tr>
<td>D</td>
<td>Pune</td>
<td>89000</td>
</tr>
<tr>
<td>A</td>
<td>Delhi</td>
<td>87000</td>
</tr>
<tr>
<td>D</td>
<td>Hyderabad</td>
<td>85000</td>
</tr>
<tr>
<td>A</td>
<td>Pune</td>
<td>78000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>89000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>70000</td>
</tr>
   
</table>

In [123]:
df.sort_values(["Store","Sales"],ascending = [True,False])


Store   Location  Sales
5     A      Delhi  87000
7     A       Pune  78000
2     A  Hyderabad  50000
0     A     Mumbai  40000
9     B       Pune  70000
1     B       Pune  45000
3     C     Mumbai  90000
8     C     Mumbai  89000
4     D       Pune  89000
6     D  Hyderabad  85000

<a id='ranking'></a>
## 4. Rank

<table align="left">
    <tr>
        <td width="6%">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>17. Create a column 'Rank_sales' which contains the rank of each store based on sales of the product in ascending order
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the dataframe given below:**
   
<table>
<tr>
<th>Store</th>
<th>Location</th>
<th>Sales</th>
</tr>
<tr>
<td>A</td>
<td>Mumbai</td>
<td>40000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>45000</td>
</tr>
<tr>
<td>A</td>
<td>Hyderabad</td>
<td>50000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>90000</td>
</tr>
<tr>
<td>D</td>
<td>Pune</td>
<td>89000</td>
</tr>
<tr>
<td>A</td>
<td>Delhi</td>
<td>87000</td>
</tr>
<tr>
<td>D</td>
<td>Hyderabad</td>
<td>85000</td>
</tr>
<tr>
<td>A</td>
<td>Pune</td>
<td>78000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>89000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>70000</td>
</tr>
   
</table>

In [124]:
#output

In [130]:
df["Rank_sales"]=df.Sales.rank(method='min')

In [129]:
df.sort_values("Rank_sales", inplace = True)
df

Store   Location  Sales  Rank_sales
0     A     Mumbai  40000         1.0
1     B       Pune  45000         2.0
2     A  Hyderabad  50000         3.0
9     B       Pune  70000         4.0
7     A       Pune  78000         5.0
6     D  Hyderabad  85000         6.0
5     A      Delhi  87000         7.0
4     D       Pune  89000         8.0
8     C     Mumbai  89000         8.0
3     C     Mumbai  90000        10.0